### ISSUE TITLE
1.2.1. no longer working

### ISSUE THREAD

**Issue by EvilEls** [frankjoke/ioBroker.km200#18]
Hi, I upgraded to 1.2.1. today with the result that the adapter does no longer gets any data.
I tried to reload the adapter and suddenly the entire km200 object was gone.
Now I try to find out, what passwords could be.
I assume that `Gerätepasswort` is what I can find in the info menu of the device.
But what is `Privates Passwort` ? Is it the password for the web portal?
The adapter not even in debug mode gives any hint if the passwords are right or wrong.
Output is always the same. No matter if I put correct passwords in or just a random string.
Could you please add a bit more verbosity to debug mode?

```
km200.0 | 2019-03-08 00:37:28.529 | info | KM200 finished creation of 0 states: []
-- | -- | -- | --
km200.0 | 2019-03-08 00:37:28.527 | info | Services found: 41
km200.0 | 2019-03-08 00:37:28.526 | warn | Did not get any Services from KLM200!: {}
```

**Comment by frankjoke** [comment]
The Gerätepasswort  is written on the device with the www-xxx-yyy-zzz above the mac and the private password is the one you use with the web or mobile app!

**Comment by frankjoke** [comment]
If you still have the accesskey (64 hex characters) it should work as well as the 'Gerätepasswort'!

**Comment by frankjoke** [comment]
If you have access key from old config just enter anything in password!
I update adapter to new version which will not stop if password is empty!
