### ISSUE TITLE
switchPrograms missing

### ISSUE THREAD

**Issue by tp1de** [frankjoke/ioBroker.km200#19]
Hi Frank, isn't this working?

switch (info.type)
    {
    case "switchProgram":
        {
        json = JSON.stringify(info.switchPoints);
        setState(state,json);
        break;
        }

**Comment by frankjoke** [comment]
That's what I tried to do originally but I do not get any data when I want to read the program, so there is nothing to convert in json!
I originally logged and traced all answers and the current selection is what I found out.

You know, the communication items are encrypted, so you don't see what the request contains inside, just the link. Most probably you need to provide additional data to get the right information.

**Comment by tp1de** [comment]
This example script for dhw1 swithPrograms with old hex-key is working:

const MCrypt = require('mcrypt').MCrypt;
key = " xxxxxxxx ";
server = "http://192.168.178.31:80";
field =  "/dhwCircuits/dhw1/switchPrograms/A",
get(field);

function get(feldname)
{
    var url1  = server + feldname;
    var request = require('request');
    console.log(url1);
    options = 
    {
     url: url1,
      method: 'GET',
      timeout: 4000,
      headers: 
      {
        'Accept': "application/json",
        'agent': 'TeleHeater/2.2.3',
        'User-Agent': "TeleHeater/2.2.3" 
      }
    };
     request(options, callback); 
}

//********************************************************
function callback(error, response, body)
{ 
   if (!error && response.statusCode == 200) 
   {
        Daten(body);
   }
   else
   {
        console.warn('*** http Fehler:');
   }
}

//********************************************************
function Daten(body)
{
    var b = new Buffer(body, 'base64');
    var aeskey = new Buffer(key, 'hex');
    var Ecb = new MCrypt('rijndael-128', 'ecb');

    Ecb.open(aeskey); 

    var s = Ecb.decrypt(new Buffer(b, 'hex')).toString('utf8');
    while (s.charCodeAt(s.length - 1) === 0)
    s = s.slice(0, s.length - 1);
    
    var info = JSON.parse(s);
   
    feldname  = info.id;
     
    switch (info.type)
    {
    case "switchProgram":
        {
        json = JSON.stringify(info.switchPoints);
        console.log(json);
        break;
        }     
    }
}

**Comment by frankjoke** [comment]
Hi  again, thanks for the example!
It helped me to find the problem which was just looking at the wrong field when scanning the ressources because the switch-program (and recording) has a a special id to look for the data.

I did not manage to get recordings but just build with a raspberry a wireless router where I can put wireshark's pcap on it and see the communication between bosch and the km200 because I found out that the api for the web or mobile app talking to the central server is different than the one from central server talking to the device.

Can you load 1.2.3 from git and check if it's working for you as well? If yes I will update the npm as well.

**Comment by tp1de** [comment]
Ich antworte mal auf Deutsch:

1. Ja die neue Version 1.2.3 funktioniert soweit - die switchPrograms Daten sind da.
2. Leider nur im Lesen Modus - Würde gerne auch Schreiben . Ist das machbar?

Ich lasse den Adapter im 5 Minuten-Intervall laufen. Da ich die Regelung bzw. einzelne Datenpunkte exakter protokollieren möchte, lasse ich ca. 15 Datenpunkte in einem js-Skript alle 30 Sekunden updaten.
Ist vielleicht eine Überlegung wert, diese Funktion (2.Update-Intervall für diskrete Datenpunkte) mit in den Adapter zu integrieren.

Grüße Thomas

**Comment by frankjoke** [comment]
Habe schreiben extra ausgeschaltet bis ich mittels netzwerk sniffer (wird hoffentlich morgen fertig wenn ich einen wlan-stick kaufe, ist ein alter raspi ohne wlan...) anschauen kann wie es die cloud macht. Die Daten sind in einem post verschlüsselt ...
Will jetzt im Winter nicht meine Heizung nicht zerschießen  :)

**Comment by frankjoke** [comment]
p.s.: Ich versuche ja die Aufzeichnungen auch auszulesen, diese verwenden zusätzliche Optionen mit `?xxx=yyy` hinter den Adressen aber sie sind mir eben noch nicht bekannt, für diese Optionen welche die mobiule app zur cloud verwendet krieg ich nur leere arrays (so wie jetzt).
Wenn ich das einbaue kann ich checken ob auch der schnelleren update mancher Punkte möglich ist.

**Comment by tp1de** [comment]
Falls du eine Fritzbox hast, kannst den Netzwerkverkehr auch mit: http://fritz.box/html/capture.html
mitschreiben und mit Wireshark auswerten.
Dort siehst Du auch die Kommunikation mit dem Bosch(Buderus)-Server: 139.15.227.109 über den Port 5222.
Ich bin aber noch auf der Suche nach der Kommuikation vom ioBroker zum KMxxx. Sehe ich irgendwie nicht

**Comment by frankjoke** [comment]
Danke für den Tipp! Hab leider keinen Erfolg gehabt da ich zwar die Kommunikation des Browsers mit bosch/junkers/Buderus (alle verschiedenen server) gefunden aber nichts mit dem KM200.
Werde es mal mit meinem eigenbau versuchen wenn es die Zeit zulässt..
