### ISSUE TITLE
how to read recordings

### ISSUE THREAD

**Issue by tp1de** [frankjoke/ioBroker.km200#22]
Ich habe mal auf der Fritzbox den Traffic mit Buderus-Connect mitgeschnitten und kann folgendes zu recordings feststellen:

/recordings/heatSources/actualPower?interval=xxx   liest die Brennerleistung
/recordings/system/sensors/temperatures/outdoor_t1?interval=xxx  liest die Aussentemperatur

Das Intervall **xxx** ist entweder:
- ein Datum z.B.:   **2019-03-23**      --> 24 recordings als array (jede Stunde)
- ein Monat z.B.    **2019-03**           --> 28-31 recordings (jeder Tag)
- oder ein Jahr      **2019**                 --> 12 recordings (jeder Monat)

Im recordings-array werden 2 Werte ausgegeben: y- und c-Wert. Der y-Wert / 60 ist der Gasverbrauch in kWh  (nur der Januar-Wert stimmt nicht mit Buderus-Connect überein??) bzw. bei der Aussentemperatur ist der y- durch den c-Wert zu teilen. Das ergibt dann die Durchschnittstemperatur. Beim Tagesintervall ist C=60, beim Monatsintervall 24*60=1440. Nur die c-Monatswerte sind nicht richtig plausibel .....

Ich hoffe, dass dies weiterhilft zur Vervollständigung des Adapters.

Gruß Thomas

**Comment by tp1de** [comment]
**Ergänzung:  Funktioniert analog für alle recordings !**

Tages- und Stundenwerte liegen für den aktuellen Monat und den Vormonat vor.
Ansonsten Monatswerte.

**Comment by frankjoke** [comment]
tp1de, in der jetzigen Version des Adapters kann er die Daten schon auslesen, genau mit diesen Befehlen!

Beobachte im Forum die Diskussion für den Adapter, dann wirst dort die Neuigkeiten finden.
https://forum.iobroker.net/topic/3519/adapter-f%C3%BCr-buderus-km200-und-eventuell-auch-anderen-kmxxx/146
