### ISSUE TITLE
Cannot update "dhwCircuits/dhw1/switchPrograms" successfully 

### ISSUE THREAD

**Issue by EvilEls** [frankjoke/ioBroker.km200#23]
Hi,
I started the adapter and changed a single number (from 900 to 600) in the JSON readout of 
`dhwCircuits/dhw1/switchPrograms/A`

The log returns:
`warn | Set KM200 err: 'request for  http://192.168.0.50/dhwCircuits/dhw1/switchPrograms/A had status 400/Bad  Request other than supported 200,204'`

Settings for `dhwCircuits/dhw1/switchPrograms/A` are not changed.

When I try to update `dhwCircuits/dhw1/switchPrograms/A` with the very same value that was present right after start of the adapter (without any changes to the JSON), I get the same error.

Tried with different data types but it didn't work. 
Always getting this error.

**Comment by mcm1957** [comment]
Please indicate if this issue still exists with latest version (2.0.5)

Please add all related versions
adapter version:
admin version:
js-controller version:
node version:
operating system and version:
