### ISSUE TITLE
Upgrade to 1.01 fails

### ISSUE THREAD

**Issue by EvilEls** [frankjoke/ioBroker.km200#4]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'iobroker.km200@1.01',
1 verbose cli   '--production',
1 verbose cli   '--prefix',
1 verbose cli   '/opt/iobroker' ]
2 info using npm@5.4.2
3 info using node@v6.11.3
4 verbose npm-session 771110c9e4132b90
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://registry.npmjs.org/iobroker.km200 858ms
8 silly registry:manifest no matching version for iobroker.km200@1.01 in the cache. Forcing revalidation
9 http fetch GET 304 https://registry.npmjs.org/iobroker.km200 292ms (from cache)
10 silly fetchPackageMetaData error for iobroker.km200@1.01 No matching version found for iobroker.km200@1.01
11 verbose type range
12 verbose stack iobroker.km200: No matching version found for iobroker.km200@1.01
12 verbose stack     at pickManifest (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/npm-pick-manifest/index.js:61:11)
12 verbose stack     at fetchPackument.then.packument (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/manifest.js:51:18)
12 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
12 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
12 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
12 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
12 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
12 verbose stack     at Async._drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
12 verbose stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
12 verbose stack     at Immediate.Async.drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
12 verbose stack     at runCallback (timers.js:672:20)
12 verbose stack     at tryOnImmediate (timers.js:645:5)
12 verbose stack     at processImmediate [as _immediateCallback] (timers.js:617:5)
13 verbose cwd /opt
14 verbose Linux 4.9.35-v7+
15 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "iobroker.km200@1.01" "--production" "--prefix" "/opt/iobroker"
16 verbose node v6.11.3
17 verbose npm  v5.4.2
18 error code ETARGET
19 error notarget No matching version found for iobroker.km200@1.01
20 error notarget In most cases you or one of your dependencies are requesting
20 error notarget a package version that doesn't exist.
21 verbose exit [ 1, true ]

**Comment by frankjoke** [comment]
The Problem was that npm did not have version 1.01, only Git had it!
