### ISSUE TITLE
Last call on your copyright infringement

### ISSUE THREAD

**Issue by skyslasher** [frankjoke/ioBroker.km200#40]
Hello Frank,

on 05.06.2020 I sent you an email regarding the copyright infringement of your code: Using my coding without adhering to the MIT license that requires to mention me in derived works. I politely asked you to respect the license and add my name to the authors list.
No reply from your side.
Contacting you again on 25.06. I requested you to take my name on the authors list.
No reply.

Because of this, I open up the issue here.

I hereby request you to take my name to the authors list of this repository, since it relies on derived work of my coding:
https://ssl-account.com/km200.andreashahn.info/downloads/km200_php.zip
If you not adhere to this request within the next 7 days, I will let GitHub take down this repository because of copyright infringement. To be clear: I will not do this because I dislike your work or Open Source in general, this will be because of your ignorance of adhering to licenses and respecting other people’s work you build your work upon.

I described my work in these blogposts:
https://www.andreashahn.info/2014/07/kernthema-am-eigenen-leibe
https://www.andreashahn.info/2014/08/easycontrol-pro-unter-der-lupe-oder-m

You even pointed to my site (https://ssl-account.com/km200.andreashahn.info/) that is providing the access key and the coding with the MIT license in older versions of your code:
https://github.com/frankjoke/ioBroker.km200/blob/e42f758644b3c4fa7c7026b16b6ffaea9de088f9/km200.js#L57

More current versions implement my initial coding (containing the secret km200_crypt_md5_salt) that was taken down by the IP Symcon forum admins due to a request by Bosch Thermotechnik. This coding was copy&pasted in the net, with references to me. Your code here even uses the same german comments:
Initial coding by me, copied by the FHEM guys:
https://forum.fhem.de/index.php?topic=25540.0
Current coding here:
https://github.com/frankjoke/ioBroker.km200/blob/master/km200.js#L103

Regards
Andreas

**Comment by frankjoke** [comment]
Dear Andreas! 
Sorry, I am neither Ignorant nor do I want to infringe any copyright.
Luckily I got the git-issue posted by telegram because I did not see any mail (spam folders mails are kept only for a week).

Anyhow, you welcome to get into the readme and package.json, just provide me your name/email to be mentioned as Author and a text you want to be places into readme.

I look often to FEHM to translate it to javascript to be used then with iobroker.
I do not benefit from it at all aside that I can use it for my own KM200 as well!

p.s.: We can talk also German :)

**Comment by frankjoke** [comment]
I updated files (package.json and readme's to what I believed need to be done. Let me know if it is OK.

**Comment by frankjoke** [comment]
Andreas, can you let me know if I can close this issue now????

**Comment by skyslasher** [comment]
Hi Frank,

thank you for taking care on this issue. With your changes, you attributed my **authorship** in the package.json and readme. What is still missing is the **copyright** note on the communications and crypto procedures, that, according to the originating MIT license, shall be included in each distribution of that code. As you are also using the MIT license, this is easy. Please add this copyright disclaimer underneath your copyright notice line "Copyright (c) 2016-2020 Frank Joke frankjoke@hotmail.com":
Includes communications and crypto routines copyright (c) 2014 Andreas Hahn km200@andreashahn.info

Thank you and best regards
Andreas

**Comment by frankjoke** [comment]
I added it in readme and license.
Please check and close case if OK.
BR Frank

**Comment by skyslasher** [comment]
Thanks!
