### ISSUE TITLE
Warning in log

### ISSUE THREAD

**Issue by unstressable** [frankjoke/ioBroker.km200#45]
km200.0 | 2020-10-25 11:47:48.458 | warn | (16073) adapter.objects.getObjectList is deprecated, and will be removed in the future. Please use adapter.getObjectList/Async. Report this to Developer!
-- | -- | -- | --

**Comment by EvilEls** [comment]
Same here

```
km200.0	2020-10-29 14:07:38.391	warn	(4283) adapter.objects.getObjectList is deprecated, and will be removed in the future. Please use adapter.getObjectList/Async. Report this to Developer!
km200.0	2020-10-29 14:07:38.336	info	(4283) starting. Version 2.0.3 in /opt/iobroker/node_modules/iobroker.km200, node: v12.19.0, js-controller: 3.1.6
```

**Comment by frankjoke** [comment]
This is a known 'feature' of new js-controller and I will implement a changed version before next big version of js-controller will really remove the function!
