### ISSUE TITLE
Warnung im Protokoll

### ISSUE THREAD

**Issue by DaisyMaus** [frankjoke/ioBroker.km200#81]
Hallo. Ich bekomme jeden Tag immer wieder Warnungen und weis aber nicht was ich falsch mache. Der Adapter lief seit Monaten und auf einmal die Warnungen. Ich nutze die aktuellste Version 2.0.3.

Gruss
Daisy

km200.0 | 2022-04-07 14:00:46.044 | warn | This object will not be created in future versions. Please report this to the developer.
-- | -- | -- | --
km200.0 | 2022-04-07 14:00:46.044 | warn | Object system.systemType is invalid: obj.common.states has an invalid type! Expected "object", received "string"
km200.0 | 2022-04-07 14:00:45.646 | warn | This object will not be created in future versions. Please report this to the developer.
km200.0 | 2022-04-07 14:00:45.646 | warn | Object system.healthStatus is invalid: obj.common.states has an invalid type! Expected "object", received "string"
km200.0 | 2022-04-07 14:00:45.588 | warn | This object will not be created in future versions. Please report this to the developer.
km200.0 | 2022-04-07 14:00:45.588 | warn | Object system.bus is invalid: obj.common.states has an invalid type! Expected "object", received "string"
km200.0 | 2022-04-07 14:00:45.527 | warn | This object will not be created in future versions. Please report this to the developer.
km200.0 | 2022-04-07 14:00:45.527 | warn | Object system.brand is invalid: obj.common.states has an invalid type! Expected "object", received "string"
km200.0 | 2022-04-07 14:00:45.412 | warn | State value to set for "km200.0.heatingCircuits.hc1.temporaryRoomSetpoint" has value "-1" less than min "5"
km200.0 | 2022-04-07 14:00:45.398 | warn | State value to set for "km200.0.heatingCircuits.hc1.temporaryRoomSetpoint" has value "-1" less than min "5"
km200.0 | 2022-04-07 14:00:45.111 | warn | This object will not be created in future versions. Please report this to the developer.
km200.0 | 2022-04-07 14:00:45.111 | warn | Object heatingCircuits.hc1.switchProgramMode is invalid: obj.common.states has an invalid type! Expected "object", received "string"
km200.0 | 2022-04-07 14:00:44.907 | warn | This object will not be created in future versions. Please report this to the developer.
km200.0 | 2022-04-07 14:00:44.907 | warn | Object heatingCircuits.hc1.suWiSwitchMode is invalid: obj.common.states has an invalid type! Expected "object", received "string"
km200.0 | 2022-04-07 14:00:44.848 | warn | This object will not be created in future versions. Please report this to the developer.
km200.0 | 2022-04-07 14:00:44.848 | warn | Object heatingCircuits.hc1.status is invalid: obj.common.states has an invalid type! Expected "object", received "string"
km200.0 | 2022-04-07 14:00:44.667 | warn | This object will not be created in future versions. Please report this to the developer.
km200.0 | 2022-04-07 14:00:44.667 | warn | Object heatingCircuits.hc1.operationMode is invalid: obj.common.states has an invalid type! Expected "object", received "string"
km200.0 | 2022-04-07 14:00:44.545 | warn | State value to set for "km200.0.heatingCircuits.hc1.fastHeatupFactor" has value "0" less than min "1"
km200.0 | 2022-04-07 14:00:44.544 | warn | This object will not be created in future versions. Please report this to the developer.
km200.0 | 2022-04-07 14:00:44.543 | warn | Object heatingCircuits.hc1.holidayMode.activated is invalid: obj.common.states has an invalid type! Expected "object", received "string"
km200.0 | 2022-04-07 14:00:44.530 | warn | State value to set for "km200.0.heatingCircuits.hc1.fastHeatupFactor" has value "0" less than min "1"
km200.0 | 2022-04-07 14:00:44.467 | warn | This object will not be created in future versions. Please report this to the developer.
km200.0 | 2022-04-07 14:00:44.467 | warn | Object heatingCircuits.hc1.currentSuWiMode is invalid: obj.common.states has an invalid type! Expected "object", received "string"
km200.0 | 2022-04-07 14:00:44.327 | warn | This object will not be created in future versions. Please report this to the developer.
km200.0 | 2022-04-07 14:00:44.327 | warn | Object heatingCircuits.hc1.activeSwitchProgram is invalid: obj.common.states has an invalid type! Expected "object", received "string"
km200.0 | 2022-04-07 14:00:00.026 | warn | Adapter will exit in latest 1 sec with code false!

</body>
</html>

**Comment by frankjoke** [comment]
I just tried to change the file directly on git, if you download latest git it should work!
