### ISSUE TITLE
Warnung bei Neustart

### ISSUE THREAD

**Issue by Jo59Devs** [frankjoke/ioBroker.km200#83]
Seit geraumer Zeit gibt es bei jedem Neustart folgende Warnungen:

km200.0 | 2022-08-19 08:02:05.699 | warn | This object will not be created in future versions. Please report this to the developer.
km200.0 | 2022-08-19 08:02:05.698 | warn | Object  heatingCircuits.hc1.suWiSwitchMode is invalid: obj.common.states has an  invalid type! Expected "object", received "string"
km200.0 | 2022-08-19 08:02:05.675 | warn | This object will not be created in future versions. Please report this to the developer.
km200.0 | 2022-08-19 08:02:05.674 | warn | Object heatingCircuits.hc1.status is invalid: obj.common.states has an invalid type! Expected "object", received "string"
km200.0 | 2022-08-19 08:02:05.573 | warn | This object will not be created in future versions. Please report this to the developer.
km200.0 | 2022-08-19 08:02:05.572 | warn | Object heatingCircuits.hc1.operationMode is invalid: obj.common.states has an invalid type! Expected "object", received "string"

**Comment by DeeCee42** [comment]
Hi,
bei mir auch, und noch einige mehr in ähnlicher Form.
Dazu kommt bei jeder Abfrage eine Warnung: KM200.get service parameter not as requested 'undefined'
Scheint aber insgesamt noch zu funktionieren.
Bleibt ein toller Adapter, der mir schon viele nützlichen Info's über die Hzg geliefert hat.

**Comment by frankjoke** [comment]
Der Grund sind die neuen js-controller. Bitte adapter mal von Git laden, dort hab ich schon testweise was geändert!

**Comment by DeeCee42** [comment]
Hi frankjoke,
ich habe den neuesten Adapter von Github geholt. Es läuft los aber nach ca. 90s kommt:

INit getservices error TypeError: Cannot create property '0' on boolean 'false' at /opt/iobroker/node_modules/iobroker.km200/km200.js:453:61 at Array.forEach (<anonymous>) at /opt/iobroker/node_modules/iobroker.km200/km200.js:453:37 at /opt/iobroker/node_modules/@frankjoke/myadapter/myAdapter.js:819:53

Und:
Adapter km200 initialization finished with 0 states.

Damit keine Daten vom KM200. Any idea?
