### ISSUE TITLE
Wärmepumpe Kühlmodus

### ISSUE THREAD

**Issue by MWeller177** [frankjoke/ioBroker.km200#86]
Hallo,

bei mir läuft der Adapter wie er soll, hierfür schon mal ein großes Dankeschön!

Unsere Wärmepumpe hat allerdings auch eine Kühlfunktion.
Diese möchte ich gerne über den Adapter einschalten können.

Wenn ich an der Wärmepumpe den Kühlmodus aktiviere, ändert sich der Wert der Variable km200.0.heatingCircuits.hc1.suWiSwitchMode auf "-1"
wenn ich hier über ein Script die "-1" eintrage, geht das aber leider nicht.

Gibt es hier eine Möglichkeit das anzupassen?

grüße!

**Comment by frankjoke** [comment]
Das '-1' scheint der KM200 als 'nicht definiert' oder 'unbekannt' zu verwenden, bekomme das nähmlich auch bei anderen Werten wenn sie nicht vorhanden sind. 

Bei der Initialisierung des Adapters sucht dieser nach allen Werten die der KM200 übermitteln kann und bekommt Info über die Datenpunkte die der Adapter bei dem State den er kreiert als 'native.km200' anhängt. Schau mal bei einem der states im Objektbrowser mittels dem Pencil auf die Definition, z.B. bei mir km200.0.dhwCircuits.dhw1.operationMode = `
{
  "common": {
    "name": "dhwCircuits.dhw1.operationMode",
    "read": true,
    "write": true,
    "state": "state",
    "role": "level",
    "type": "number",
    "unit": "",
    "states": {
      "0": "Off",
      "1": "high",
      "2": "HCprogram",
      "3": "ownprogram"
    },
    "min": 0,
    "max": 3
  },
  "type": "state",
  "_id": "km200.0.dhwCircuits.dhw1.operationMode",
  "native": {
    "km200": {
      "id": "/dhwCircuits/dhw1/operationMode",
      "type": "stringValue",
      "writeable": 1,
      "recordable": 0,
      "value": "ownprogram",
      "allowedValues": [
        "Off",
        "high",
        "HCprogram",
        "ownprogram"
      ],
      "valIs": "states"
    }
  },
  "from": "system.adapter.km200.0",
  "user": "system.user.admin",
  "ts": 1671733118173,
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}`

Diese Info verwendet der Adapter aber der KM200 schickt leider auch ein -1 wenn der Wert nicht dem allowed values (0-?) entspricht.

Ich kann da nix machen da ich nur nach den Infos vom KM200 im Adapter agieren kann.

**Comment by MWeller177** [comment]
Okay sowas hab ich mir schon gedacht.
Die Wärmepumpe hat 4 Auswahlmöglichkeiten, KM200 leider nur 3:

off (0) - sommer
automatic (1) - auto
forced (2) – heizen

Die Einstellung Kühlen führt leider zu einem nicht definierten Wert, also -1

**Comment by frankjoke** [comment]
Kannst ja mal '3' probieren und schauen obs der KM200 überträgt .... wenn bei 'writeable' 1 steht!
