### ISSUE TITLE
***An DIESEM Adapter wird anscheinend nicht mehr gearbeitet***

### ISSUE THREAD

**Issue by mbhomie007** [frankjoke/ioBroker.km200#87]
Als kleiner Tipp:
Da an diesem Adapter anscheinend nicht mehr gearbeitet wird, habe ich mich nach einer Alternative umgesehen:

https://github.com/tp1de/ioBroker.ems-esp

Dieser Adapter wird fortlaufend weiterentwickelt und auch meine Buderus HRV Lüftungsanlage ist ebenso integriert. 👌

**Comment by Apollon77** [comment]
Hm ... interessantes Statement ... sollte das nicht eher vom Adapter-Entwickler kommen?

Ansonsten: Für wlche Schnittstellen genau ist es denn ein Replacement - nur für ems-esp oder auch andere?

**Comment by mbhomie007** [comment]
> Hm ... interessantes Statement ... sollte das nicht eher vom Adapter-Entwickler kommen?

Macht für mich jedenfalls den Anschein, wenn ich mir die Bug Reports anschaue. 
Reaktionen kamen auch nicht... 
Aber kann ja jeder selber interpretieren wie er möchte
 
> Ansonsten: Für wlche Schnittstellen genau ist es denn ein Replacement - nur für ems-esp oder auch andere?

Läuft bei mir z. B. einwandfrei mit meiner Buderus Wärmepumpe und Buderus Lüftungsanlage

**Comment by frankjoke** [comment]
Ja, indirekt ist dem so und ich bin froh einen anderen Adapter zu sehen welcher hier übernehmen kann da ich den Adapter nicht mehr testen kann.

Ich hatte damals vor einigen Jahren den Adapter geschrieben (von FHEM/PHP auf Javascript portiert) da es damals keine andere Möglichkeit gab auf die Daten zuzugreifen (Damals war es auch noch im Buderus-Portal und nicht in Bosch-Händen).

In der Wohnung wo ich den Adapter hatte wurde die Gas-Therme durch eine Wärmepumpe eines anderen Herstellers ersetzt und ich kann jetzt keine Tests mehr durchführen, auch kann ich den oben genannten Adapter nicht mehr testen.

**Comment by mbhomie007** [comment]
Vielen Dank für deine Rückmeldung.

Wollte dir damit auch nicht zu nahe treten, sondern nur für (zukünftige) User eine Info geben.

Notfalls könnte man ja noch den Marker "Archived by owner" setzen.

Danke dir!
